version: '3.8'

services:
  fdo-api:
    image: ghcr.io/iconidentify/ada32-toolkit:latest
    container_name: fdo-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
