# Koyeb Deployment Configuration
# This file configures the FDO API deployment on Koyeb

name: fdo-api
type: web
source:
  type: git
  repository: https://github.com/iconidentify/ada32-toolkit
  branch: master
  workdir: api

ports:
  - port: 8000
    public: true
    protocol: http

env:
  - name: PYTHONPATH
    value: /app
  - name: LOG_LEVEL
    value: INFO

# Health check for the API
healthcheck:
  type: http
  path: /health
  port: 8000
  interval: 30s
  timeout: 10s

# Resource allocation (free tier)
resources:
  cpu: 0.1
  memory: 512MB

# Scaling (single instance for free tier)
scaling:
  min: 1
  max: 1
